### ISSUE TITLE
Add support for charset

### ISSUE THREAD

**Issue by nschonni** [editorconfig/editorconfig-notepad-plus-plus#1]
NPP (6.3?) supports the setting New document's encoding.
Not sure if there is a programmatic why of interacting with the encoding menu though.

**Comment by tvb** [comment]
+1

**Comment by ffes** [comment]
With `NPPM_GETBUFFERENCODING` and `NPPM_SETBUFFERENCODING` (documented at http://docs.notepad-plus-plus.org/index.php/Messages_And_Notifications) and maybe use `IDM_FORMAT_CONV2_AS_UTF_8` and alike it can be done.

Not sure what the best moment (in the plugin, that is) is to do this.

**Comment by ffes** [comment]
For the record: https://github.com/editorconfig/editorconfig/issues/87 is dup of this issue

**Comment by nschonni** [comment]
Closing as mentioned when @xuhdev cloned this over to the other tracker, this tracker wasn't supposed to be used.
