### ISSUE TITLE
Trim trailing whitespace is not working

### ISSUE THREAD

**Issue by dangelov** [editorconfig/editorconfig-notepad-plus-plus#11]
Hey there,

Thanks for your work on this plugin! I've noticed that it doesn't correctly read/respect `trim_trailing_whitespace`. I've tested on Windows 7, 32-bit Notepad++, both the editor and this plugin using the latest version. The other options seem to be respected, as I can see a newline being forced when I have it set, but the trailing whitespace is never trimmed.

**Comment by ffes** [comment]
Could it be you are suffering from the problem fixed by #10

**Comment by dangelov** [comment]
I'm running 0.3.1 and the issue is (still) there. Do I need to install from source to get #10, or has it already been merged and released?

**Comment by ffes** [comment]
The fixed code has been merged in the repo. But I am afraid I will be possible to release 0.3.2 before Christmas or even before New Year.

**Comment by dangelov** [comment]
Got it, thanks!

**Comment by kaselis** [comment]
Any update on this?

**Comment by ffes** [comment]
Version 0.4.0 had been released. This release should solve this issue, therefore I am closing this issue.

Note that the plugin is not yet available in the builtin `Plugin Admin` of Notepad++. I opened notepad-plus-plus/nppPluginList#63 to update that. When the plugin will be available in Notepad++ itself is beyond us, but you can download and manually install it from the [releases page](https://github.com/editorconfig/editorconfig-notepad-plus-plus/releases/tag/v0.4.0).
