### ISSUE TITLE
Show current active settings

### ISSUE THREAD

**Issue by ffes** [editorconfig/editorconfig-notepad-plus-plus#15]
Sometimes it is very useful to have some form of feedback which editorconfig settings are currently active. Adding a dialog/messagebox to show all those settings would solve this.

**Comment by dail8859** [comment]
Would something simple such as this be sufficient, or did you have a different idea in mind?

![ec_settings](https://user-images.githubusercontent.com/3694843/36461497-db798b5c-168b-11e8-8e3a-8362fd4d7ffd.PNG)
