### ISSUE TITLE
Add support for trim_trailing_whitespace

### ISSUE THREAD

**Issue by atwellpub** [editorconfig/editorconfig-notepad-plus-plus#2]
I'm trying at the moment to get a file to recognize my .editorconfig file but it doesn't seem to recognize it. It may be user error. 

I've discovered this plugin because I would really like to have noteplad++ automatically trim whitespace on save without the use of a macro.

**Comment by ffes** [comment]
Should not be too hard to implement for someone who knows the core lib. All that is needed is something like (semi-pseudo-code):
```c
case NPPN_FILEBEFORESAVE:
   if (remove_trailing_space)
      SendMessage(hWnd, NPPM_MENUCOMMAND, 0, IDM_EDIT_TRIMTRAILING);
   break;
```

And `menuCmdID.hpp` needs to be updated

**Comment by xuhdev** [comment]
@ffes Can you make a pull request? Thanks!

**Comment by ffes** [comment]
I'll see what I can do. I have never tried to build the core lib or the plugin itself.

**Comment by ffes** [comment]
Still have to do some final things before I can prepare a PR, but I have a working version.
