### ISSUE TITLE
Modifying file unfolds code

### ISSUE THREAD

**Issue by dail8859** [editorconfig/editorconfig-notepad-plus-plus#20]
When whitespace is trimmed, or a final newline is inserted or removed, the document's fold state is not always maintained.

### Steps to Reproduce the Issue
1. Create an `.editorconfig` file as follows:
```
root=true
[*]
trim_trailing_whitespace=true
insert_final_newline=true

```
2. Create a C++ file in the same directory as follows:
```cpp
int dosomething(void) {
	// add whitespace to the right >>>          
}

int main(void) {
	return 0;
}
```
3. Fold the code at the 2 fold points. It will now look like this:
![capture2](https://user-images.githubusercontent.com/3694843/36132862-ae68a156-1047-11e8-849c-ed4d1af92e8e.PNG)

4. Save the file
5. The 2 fold points open up

### Expected Behavior
The folding to stay the same once saved. It can be very distracting to have code move around when you save the file.

### Debug Information

Tested using latest HEAD (85d675783011893a53c78f98b0a25155ef64ab7d)

```
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BetterMultiSelection.dll DoxyIt.dll DSpellCheck.dll ElasticTabstops.dll LuaScript.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppEditorConfig.dll NppExport.dll PluginManager.dll PythonScript.dll Scintillua++.dll SurroundSelection.dll 
```

**Comment by xuhdev** [comment]
Can you do the following testing: (1) Fold code. (2) Click on "Edit"-->"Trim Whitespace...". Does the code unfold?

**Comment by dail8859** [comment]
> Does the code unfold?

Yes the code does unfold.

**Comment by xuhdev** [comment]
Then I think this is a bug in Notepad++, not on our side. Can you report it to https://github.com/notepad-plus-plus/notepad-plus-plus/issues ?

**Comment by dail8859** [comment]
At first I tended to agree it was a Notepad++ issue, however the use-case seems to be slightly different. If you run it by the menu, then a user is knowingly having Notepad++ edit the file for them which could potentially unfold code. I see this plugin as a silent and transparent way to keep code formatting sane, so the edits to the file should be the same and should go unnoticed by the user. 

Plus the fix to this is fairly straight forward and simple as you can see in the associated PR.

**Comment by xuhdev** [comment]
I see. I will comment on the PR -- let's try to fix this.
