### ISSUE TITLE
Build from source on linux?

### ISSUE THREAD

**Issue by flurbius** [editorconfig/editorconfig-notepad-plus-plus#22]
The readme implies that this plugin can only be built on windows and the result is a dll.

Maybe someone here can answer this for me, is it possible to create a .so for notepadqq (I understand it's the linux version of notepad++).

I haven't tried yet but I may do so in the next few days, I will reply here if I do.

**Comment by ffes** [comment]
To be honest up till you mentioned notepadqq I had never heard of it. So I really don't know.

Slightly off-topic... Looks nice to install on my Ubuntu laptop though. But on Linux I mostly use vscode, vim or the editor that comes with the desktop environment.

**Comment by flurbius** [comment]
Yes I was using it but now vscode is so comfortable, I only use nqq for
non-coding tasks.   Btw I went to check on the repository and it is not
related to notepad++ but it was inspired by it.

**Comment by xuhdev** [comment]
@flurbius I looked it up. It looks like it is not supposed to be compatible with Notepad++, and it's extensions are actually on the Node.js platform <http://notepadqq.altervista.org/docs/0.50/Objects/NotepadqqApi/>. I'll close this for now. Thank you any way for your mention.
