### ISSUE TITLE
end_of_line not working

### ISSUE THREAD

**Issue by mirnovak** [editorconfig/editorconfig-notepad-plus-plus#24]
The .editorconfig's setting
`end_of_line = lf`
is not applied when saving the file.

How to reproduce: Open a file, change EOLs to CRLF, save the file. 
The CRLFs are not converted to LF.
The other features e.g. trim_trailing_whitespace work fine.

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
indent_style = tab
tab_width = 4
trim_trailing_whitespace = true
charset = utf-8
```

**Comment by ffes** [comment]
You're right.

There are commands in the UI to convert the line endings. They are probably available as API messages. And I need to lookup what the Scintilla or N++ messages are to get the current type of line ending.

**Comment by dail8859** [comment]
> They are probably available as API messages.

The API is already being used to convert line endings but it does it only when *switching to a file*, not when saving it.

**Comment by ffes** [comment]
But that only **sets**  the line ending, doesn't **converts**  the file. It actually can result in different line ending in one file.

In the statusbar you can **convert**  the line ending of the entire file, by right clicking the current format. Can also be done in the edit menu.  `NPPM_SETBUFFERFORMAT` is probably used for that.  Shouldn't be hard to incorporate in the save process. I will see what I can do.

**Comment by xuhdev** [comment]
Also checkout the [FAQ](https://github.com/editorconfig/editorconfig/wiki/FAQ#my-files-are-not-automatically-reformatted-the-editorconfig-plugin-is-not-working).

**Comment by ffes** [comment]
> Also checkout the FAQ.

Yes, but for me line endings is something different from reformatting the use of tabs or spaces. I would be absolutely fine when my editor fixes the line endings automatically but not when it "fixes" (often messes up) my tabs.

When you **create** a new file it should definitely set the line ending correctly. I am not sure if I can intercept only the first save. And the situation that @mirnovak describes results in different line endings in one file :-(

And I noticed that vscode forces the line ending when saving. But AFAIK vscode doesn't support different line endings in one file (which almost always is a good thing).

**Comment by dail8859** [comment]
> But that only sets the line ending, doesn't converts the file. It actually can result in different line ending in one file.

Ah yes, you are correct.

> `NPPM_SETBUFFERFORMAT` is probably used for that.

This seems to do the same thing as `SCI_SETEOLMODE` but it also updates a few of the GUI elements...this doesn't actually *convert the line endings*. You have to trigger one of the `Edit > EOL Convertion` options by using one of the following menu command constants:

- `IDM_FORMAT_TODOS`
- `IDM_FORMAT_TOUNIX`
- `IDM_FORMAT_TOMAC`

> I would be absolutely fine when my editor fixes the line endings automatically but not when it "fixes" (often messes up) my tabs.

I agree with this statement 100%!

**Comment by xuhdev** [comment]
@ffes There is a huge disadvantage when doing this on saving: Version control history is probably messed with other changes. In addition, EditorConfig in general leaves the reformatting work to lint tools that are friendly to EditorConfig. This change can break the consistency across the project.

**Comment by ffes** [comment]
I understand your point.

It is quite easy to make this an option disabled by default. That way it's up to the user to decide if he wants this behaviour or not.

Having said that I am quite convinced that the plugin for vscode always forces the line ending. I'm writing this comment on my phone so I will check tomorrow.

**Comment by ffes** [comment]
> I'm writing this comment on my phone so I will check tomorrow.

I just did that quick test:

- Created `test.txt` with `crlf` line endings in Notepad++
- Created `.editorconfig` with just `end_of_line = lf` in it
- Opened `test.txt` with Notepad++, added a few lines. This results in both `crlf` and `lf` in one file
- Closed without saving
- Opened `test.txt` in vscode
- Edited and saved
- On saving the file was converted to `lf`

**Comment by ffes** [comment]
Yesterday I opened PR #26 to fix this issue. The current implementation now is to always convert the EOL when saving the file.
