### ISSUE TITLE
init.ps1 often fails to download core-c

### ISSUE THREAD

**Issue by ffes** [editorconfig/editorconfig-notepad-plus-plus#31]
Locally and in CI `init.ps1` often fails to download the editorconfig-core-c from GitHub.

> ./init.ps1 -pcre $env:PCRE2_VERSION -edc $env:EDITORCONFIG_VERSION
> Downloading pcre2 v10.32 sources
> Extracting pcre2 v10.32 sources
> Downloading editorconfig-core-c v0.12.3 sources
> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The server did not return the file size. The URL might point to dynamic content. The Content-Length header is not available in the server's HTTP reply.

This seems to be a server error, but the regular browsers and tools like wget don't have a problem downloading it.

I have limited PowerShell knowledge, but there has to be a way to fix this in that script.

Locally I have a backup of that zip and extract it manually in the right place, but that doesn't help for CI.

**Comment by ffes** [comment]
Looking back at the commits, @ViceIce has added these (apart from this small but annoying issue) beautifully working scripts. Maybe he has an idea how to solve this issue.

**Comment by ViceIce** [comment]
I've never had this issue. 

Maybe we should add a retry count?
And for ci we schould add the downloaded zip files to AppVeyor cache.

**Comment by ffes** [comment]
I've not seen the problem anymore. Closing
