### ISSUE TITLE
Dont format empty spaces

### ISSUE THREAD

**Issue by goodandrewsoft** [editorconfig/editorconfig-notepad-plus-plus#32]
Don't format c text , like this:
```cpp
int main () {
    int y, 				ty;

    return  			0;
}
```

must be:
```cpp
int main() {
    int y, ty;

    return 0;
}
```

**Comment by ffes** [comment]
I really don't see what you are trying to report with this issue? 😮 

Is it about code in this repo? Is it result of something the plugin does wrong in your opinion?

**Comment by ffes** [comment]
No reply from the OP in over a year, so I'm closing this one.

Feel free the re-open with more details about the problem you are trying to report if it is still relevant.
