### ISSUE TITLE
Get it into Notepadd++ by default

### ISSUE THREAD

**Issue by rugk** [editorconfig/editorconfig-notepad-plus-plus#33]
I've opened an issue to get this into Notepad++ by default:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6183

**Comment by xuhdev** [comment]
Thanks! This should ease our maintenance.

**Comment by ffes** [comment]
Since the [upstream request was rejected](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6183), there is nothing we can do about it. So I'm closing this one.
