### ISSUE TITLE
Not working in latest Notepad++ build?

### ISSUE THREAD

**Issue by mukunda-** [editorconfig/editorconfig-notepad-plus-plus#34]
Not sure if I'm doing something stupid, but the latest 32-bit DLL is in the plugins folder for my 32-bit Notepad++ installation. It was working before I updated.

Debug info:
Notepad++ v7.8.2   (32-bit)
Build time : Dec  4 2019 - 01:36:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ffes** [comment]
Sorry for the late reply. Is this problem still relevant?

What version of the plugin are you using?  
v0.4.0 is the current release.  
Know that the plugin hasn't changed in over a year.

Also know that I don't test the plugin on Win7 (and as you probably know Win7 is EOL)

For me everything works as expected on N++ 7.8.5, both 32 and 64-bit

**Comment by mukunda-** [comment]
Thanks for the update. Problem still persists with N++ 7.8.5; I suppose there isn't much that should be done if it's working on a proper Windows version though.

**Comment by ffes** [comment]
I just tried on an old 2008 R2 server I still have access to... (same kernel as Win7)

I downloaded N++ minimalist 32 bit, unzipped in a temp folder and put my current production `NppEditorConfig.dll` in the `plugins\NppEditorConfig` folder and everything worked as expected.

You say it doesn't work. Could you be  a more specific the that exactly means? It the dll load? Is the dll rejected at started (happens with 32/64 mismatch). Does `Show EditorConfig settings for this file` work when you open a file in a `.editorconfig` controlled directory?

Could you try with a minimalist download in a temp folder? It runs N++ separate from your installed version.

**Comment by mukunda-** [comment]
The dll doesn't load. I tried a few different minimalist versions. It loads on version 7.5.6 or under, showing `Plugins : NppEditorConfig.dll` in the Debug Info. Newer version than that show  `Plugins: none`.

**Comment by ffes** [comment]
In v7.6 and newer the location of the plugins has changed and plugins need to go in their own subdirectory under the `plugins` folder. I assume that is the cause of your problem. For existing installations back then you needed to do this manually.

**Comment by mukunda-** [comment]
Oh, so I'm just doing it wrong. Thanks, and sorry for wasting your time.
