### ISSUE TITLE
Definition file not loaded on start and forgotten on tab blur. (#3) still exist

### ISSUE THREAD

**Issue by Spammed** [editorconfig/editorconfig-notepad-plus-plus#35]
Dear ffes,

Issue #3 happens to me.
The old problem hits me exactly as it was described.
Current Windows 10, current Notepad++ version 7.8.5.

It does not matter if other plugins are installed or not.

I will try to find time to follow your debugging tip.

**Comment by Spammed** [comment]
The problem disappears or, depending on your point of view, is solved by uninstalling Notepad++ and reinstalling it again.
When uninstalling Notepad++, you seem to have to let remove your Notepad settings.

When Notepad++ was uninstalled, I also used CCleaner to clean the registry. Unfortunately I don't know if this is necessary.

I think I will not investigate further.

Thanks for the plugin.

**Comment by ffes** [comment]
Thanks for reporting.

Since there is no proper way to debug and see if it really is an issue with the plugin or with notepad++ itself I will close this one.
