### ISSUE TITLE
Please clarify the plugin description

### ISSUE THREAD

**Issue by kkm000** [editorconfig/editorconfig-notepad-plus-plus#37]
I use .editorconfig files everywhere, so when I found it in the NPP Extension Manager list, it blew my socks off. Well, to tell the truth, I rarely wear socks, but it certainly would if I did have socks on at that time! Thank you for your work. Having EditorConfig support in NPP is great, as its own configuration for different file types in not very flexible.

The description in the NPP EM, however, is rather confusing. The link to the README in this repo is also not very helpful to the end-user, since it's more focused on building/contributing. This description

> Helps define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readibly and work nicely with version control systems.

cries for a copyedit (and a spell-check, please). It packs too much arguably irrelevant stuff into the short description. It does not tell what the EditorConfig file is, or what this plugin will do when installed. Instead, it focuses on the global structure of the project, which is perhaps one of the last things you'd care when installing a plugin. (And, parenthetically, it commits an oft-committed sin of offering a superlative _opinion_, which sets it up to backfire. “Easily [readable]” and “works nicely” are both in the eye of the beholder. If the user finds that it works more or less okay (in their _opinion_ or in their particular use case), they are less likely to be disappointed when not promised it to be “easy” and “nice.”)

Assume the user may or may not be aware what EditorConfig is; the description should be fitting for both groups. It's important to mention the actual file name `.editorconfig` at least once in the description. For me, as the the user, a description along these lines would be much more focused and helpful:

> EditorConfig is a plain text file that defines coding conventions for a project to help maintain them consistent no matter which text editor you use. This plugin adds support for .editorconfig files to Notepad++. When you install this plugin, _\*\*DESCRIBE WHAT THE USER SHOULD EXPECT\*\*_. For the EditorConfig recommended use, file format and samples, visit https://editorconfig.org/.

Sorry, I cannot fill in the placeholder, I have no idea yet... :( My guess is that the missing part will likely end up being

> it will automatically discover and apply matching .editorconfig settings to the files that you open for editing

but I am only guessing. I'll figure out; but the user should not be required to.

**Comment by ffes** [comment]
Fair point. The current text is taken straight from the website. I think the suggested text is better indeed.

This change needs to go in https://github.com/notepad-plus-plus/nppPluginList
I can do that, but will wait a bit to see if anyone else has a reaction to your suggestion.

**Comment by kkm000** [comment]
Do you suggest making a PR there, or wait a bit?

**Comment by kkm000** [comment]
Thanks again, by the way. .editorconfig settings are picked up automagically!

**Comment by ffes** [comment]
Just created notepad-plus-plus/nppPluginList#227

When that is merged, I will close this issue

**Comment by chcg** [comment]
@ffes Merged.

**Comment by ffes** [comment]
@kkm000 thanks for the suggestion. It will be used in a next version of notepad++ depending on their release schedule.

**Comment by kkm000** [comment]
Thanks!
