### ISSUE TITLE
Add support for insert_final_newline

### ISSUE THREAD

**Issue by RaYell** [editorconfig/editorconfig-notepad-plus-plus#4]
It seems like the plugin does not respect the `insert_final_newline` option in the configuration. I'd be great to have it along all other remaining editorconfig features mentioned in #1 and #2

**Comment by ffes** [comment]
Have been fiddling a bit this the various Scintilla messages and `insert_final_newline=true` sort of works. It still needs some work and it relies on `onBeforeSave()` added with #5. So I'll wait for that to be properly reviewed (and merged) before I will prepare a PR for this on.

`insert_final_newline=false` to remove the final newline is the next thing to look into.
