### ISSUE TITLE
Option to see the .editorconfig file location being used for the active file

### ISSUE THREAD

**Issue by alankilborn** [editorconfig/editorconfig-notepad-plus-plus#45]
If I go to the _Plugins_ menu and choose:

![image](https://user-images.githubusercontent.com/77065706/209151967-6bbbe659-c1ff-41a6-af8f-2a4626676161.png)

It will show me what I requested, example:

![image](https://user-images.githubusercontent.com/77065706/209152026-79d68513-a1aa-4ccb-befe-f803d71b006d.png)

However, it would be nice to also see the path to the `.editorconfig` file that is in use, generating those settings.

Is this a possible feature addition?

(Using v0.4.0.0. )

**Comment by ffes** [comment]
Note that one of the difficulties is that it is possible to have multiple `.editorconfig` files can be result in the current settings. See #40 for more information.

Closing this one as a duplicate
