### ISSUE TITLE
Doesn't seem to work with Notepad++ 8.5.2

### ISSUE THREAD

**Issue by timint** [editorconfig/editorconfig-notepad-plus-plus#48]
Hi, this plugin doesn't seem to work with Notepad++ 8.5.2. See screen captured video below.
The configuration is saying tabs but it produces spaces.

```
root = true

[*.{css,html,js,json,less,php,scss,xml}]
charset = utf-8
indent_style = tabs
indent_size = 2
trim_trailing_whitespace = true

[*.{md}]
charset = utf-8
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true
```

https://user-images.githubusercontent.com/359192/236412845-952844f9-a0c7-4fdc-a9e1-e6866cac6b6d.mp4

**Comment by xuhdev** [comment]
I can't reproduce this on Notepad++ v8.5.2. Are you sure there's not another plugin interfering?

(BTW, `[*.{md}]` should be `[*.md]`. Curly braces with only one entry are interpreted as they literally are.)

**Comment by timint** [comment]
That's annoying :( Installed plugins are basically stock.
Do you see anything that looks suspicious?

![image](https://user-images.githubusercontent.com/359192/236805282-5e6c0841-1a53-45f6-b81c-ddfc3cf93757.png)

**Comment by xuhdev** [comment]
Maybe Linter or Code Alignment? Could you try disable them all and see if things come back to normal?

**Comment by timint** [comment]
I have them all uninstalled. NppEditorConfig 0.4.0.0 is the only one enabled.
![image](https://user-images.githubusercontent.com/359192/237059876-b7828f57-d799-4d15-a3d7-ca8ad0cb34b9.png)

**Comment by timint** [comment]
I managed to reproduce this with a clean portable install of Notepad++ 8.5.2.

1. NppEditorConfig is the only plugin installed and enabled.

2. Notepad++ defaults to use 2 spaces

![image](https://github.com/editorconfig/editorconfig-notepad-plus-plus/assets/359192/4561b560-2340-4ceb-b275-4b86f28d6ec1)

3. .editorconfig set to override with tabs

```
root = true

[*.php]
charset = utf-8
indent_style = tabs
indent_size = 2
trim_trailing_whitespace = true
```
I used the following folder structure:
```
~/.editorconfig
~/subfolder/test.php
```

The result is that NppEditorConfig have no ruling over the default setting of Notepad++ (spaces).
![image](https://github.com/editorconfig/editorconfig-notepad-plus-plus/assets/359192/4e563ff8-07e1-43df-b182-d60fa7469628)

**Comment by timint** [comment]
Yes, otherwise I wouldn't see the settings refleced in the "Current EditorConfig Settings" dialog.

![image](https://github.com/editorconfig/editorconfig-notepad-plus-plus/assets/359192/9ad42c75-eb7b-44ac-8a78-5637f0ec63fe)

**Comment by timint** [comment]
I tried this on a different machine running Notepad++ 8.1.8 and all was working.
I upgraded it from within the software to 8.4.8 and .editorconfig was still working.
I then manually grabbed the latest 8.5.2 from the website.  .editorconfig stopped working.

It does seem like something have changed in the later versions of Notepad++ that affects .editorconfig.

**Comment by xuhdev** [comment]
So far I have no idea -- Kind of waiting for some inspiration to jump up and maybe other complaints. I tested with exactly the same setup as you have -- I copied your setup, with the same Notepad++ version.

**Comment by timint** [comment]
The problem persists in Notepad 8.5.3.
https://github.com/editorconfig/editorconfig-notepad-plus-plus/assets/359192/005dbd2c-f224-4474-8a78-3fbdcf9f7231

**Comment by timint** [comment]
@xuhdev I just confirmed this issue on a new computer with fresh Notepad++ 8.5.4.
When you tried to reproduce this, what were your settings under Settings -> Preferences -> Language -> Tab Settings?

**Comment by timint** [comment]
With the help of a pair of fresh eyes from the Notepad++ Community Forum the problem has been identified.

`indent_style = tabs`

should be

`indent_style = tab`

Closing this issue as not a bug. Big thank you to mpheath on the forums. I am too worn out to have spotted this myself. 🙂
https://community.notepad-plus-plus.org/topic/24631/can-anyone-confirm-this-issue-with-editorconfig

**Comment by xuhdev** [comment]
That's awesome to know! Now looking back, I didn't catch the issue because I tested with a `.md` file. Next time I should remember to use exactly the same settings :+1:
