### ISSUE TITLE
No 64bit version for Notepad++ v7

### ISSUE THREAD

**Issue by piotr-cz** [editorconfig/editorconfig-notepad-plus-plus#9]
Notepad++ v7 [is available](https://notepad-plus-plus.org/download/v7.html) in both 32bit and 64bit editions.

EditorConfig plugin v0.3.1 doesn't work in the latter one.

**Comment by ffes** [comment]
And as Don writes on the release page of Notepad++ 7 only a few 64-bit plugins exist.
https://notepad-plus-plus.org/news/notepad-7-released.html

I haven't even taken a look on how difficult it is to build 64-bit plugins and what problems to expect. I don't see myself running the 64-bit version any time soon because too many plugins are missing. So I will stick with the 32-bit for while.

Having said that, you are right. There has to be a 64-bit version of the plugin.

**Comment by piotr-cz** [comment]
I've updated Notepad++ to v7 using [Chocolatey](chocolatey.org) which automatically picked 64bit edition so without reading release notes.

I may switch to 32bit edition because at this moment even Plugin manager isn't compatible with 64bit.

**Comment by xuhdev** [comment]
I'll mark this issue on my TODO list. Thanks for the reporting!

**Comment by ameer1234567890** [comment]
If more developers like developer of this plugin makes 64bit versions, the problem of "_only a few 64-bit plugins exist_" would be resolved soon.

**Comment by ViceIce** [comment]
Hi,

I've build a x64 version from master with pcre (8.38) and editorconfig-core-c (master).
Please have a try.

If all is working, i will provied build information.

Regards
Michael

[NppEditorConfig.zip](https://github.com/editorconfig/editorconfig-notepad-plus-plus/files/1217660/NppEditorConfig.zip)

**Comment by wangqr** [comment]
I have just tried to build the x64 version. The only difference is to select the `Win64` generator in CMake, and everything works fine. So I think it is a trivial task to add it to the plugin manager list.

To add the x64 version to the plugin manager list, we need to:
- [ ] Host the x64 dll somewhere, maybe on SourceForge or GitHub release.
- [ ] Create a PR to [bruderstein/npp-plugins-x64](https://github.com/bruderstein/npp-plugins-x64), to include the meta info of this plugin.

**Comment by xuhdev** [comment]
@wangqr Awesome! Do you wanna look into #16 ?

**Comment by wangqr** [comment]
Currently this project is building using CMake, and the README.md is quite clear about how to build the plugin. Are the scripts in #16 used for automated build/release? I haven't used PowerShell scripts before, maybe I'll take a look.

**Comment by ViceIce** [comment]
Please have a look. I've prepared the scripts from #16 for automated build. I can provide them in any other language when required. ;)

We use the 64bit build on production without problems.

Regards
Michael

**Comment by tannergooding** [comment]
@ViceIce, I've been using the 64-bit version you linked above for the whole month now and haven't seen any issues.

**Comment by piotr-cz** [comment]
@ViceIce Thanks! 👍

**Comment by Predelnik** [comment]
Is there any progress on this issue? Could at least x64 version be added to releases even if build scripts are not perfect?

**Comment by chcg** [comment]
See https://ci.appveyor.com/project/xuhdev/editorconfig-notepad-plus-plus/build/1.0.3/job/n4lic6kswnt840wb/artifacts.
@xuhdev How about creation of a new release?

**Comment by chcg** [comment]
@ffes @xuhdev Do you have a timeframe to release a x64 version?

**Comment by AnyOldName3** [comment]
This is still not showing up in the plugin manager for me, but it looks like there've been no actual issues for a year.

**Comment by chcg** [comment]
@xuhdev Why is this issue closed? I see a working appveyor build, but no release yet. Appveyor artifacts are just not available for 6 month. PluginManager and N++ PluginAdmin need a zip package to add a new release version to the plugin lists.

**Comment by ffes** [comment]
Version 0.4.0 had been released. This release should solve this issue, therefore I am closing this issue.

Note that the plugin is not yet available in the builtin `Plugin Admin` of Notepad++. I opened notepad-plus-plus/nppPluginList#63 to update that. When the plugin will be available in Notepad++ itself is beyond us, but you can download and manually install it from the [releases page](https://github.com/editorconfig/editorconfig-notepad-plus-plus/releases/tag/v0.4.0).
